spring:
  application:
    name: chat_personal
  server:
    port: 8088
  data:
    mongodb:
      username: mongo
      password: mongo
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin